### ISSUE TITLE
Changement de serveur

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#58]
Le changement de serveur dans "Préférences" => "Paramètres serveur" => "Serveur JNTP", ne fonctionne pas.

**Comment by Julien-Arlandis** [comment]
C'est normal, c'est juste news et news2 qui n'acceptent pas volontairement le crossdomain (connexion depuis un autre site), par contre en mettant devnews2.nemoweb.net ça fonctionne.

**Comment by DuzzAtNemo** [comment]
Chez moi, l'interface se bloque sur "Tentative de connexion à jntp://devnews2.nemoweb.net".

**Comment by Julien-Arlandis** [comment]
devnews2 n'accepte pas non plus le cross domain je crois. Mais si tu vas sur devnews2.nemoweb.net et que tu saisis devnews.nemoweb.net cette fois ça marche.

**Comment by DuzzAtNemo** [comment]
Oui, ça marche dans le sens 'devnews2' => 'devnews', mais il y a deux anomalies :
- La barre d'URL du navigateur continue à afficher http://**devnews2**.nemoweb.net/.
- Dans la liste des articles, la sélection est placée sur l'article le plus **ancien**.

**Comment by Julien-Arlandis** [comment]
La barre d'url n'a pas à changer. Tu es toujours sur le site devnews2, mais nemo en interne se connecte sur le serveur devnews. Pour le reste devnews2 n'est pas à jour faudra retester quand le client et le serveur auront été upgradé.

**Comment by DuzzAtNemo** [comment]
OK, on laisse ce ticket en attente.

**Comment by DuzzAtNemo** [comment]
Problème résolu dans la version Nemo/0.998r.
Issue closed.
