### ISSUE TITLE
Liste noire

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#59]
1 - Dès qu'un FromName/FromMail est enregistré dans la liste noire, il me semble qu'il serait judicieux et convivial d'afficher quelques mots d'explication au-dessus de la liste, du genre : "Cliquer sur un auteur pour le retirer de la liste :" 

2 - Pour mémoire, un incident que je n'ai pas réussi à reproduire : apparition d'entrées "null" qui ne sont pas effaçables par la croix rouge.

http://news.nemoweb.net/jntp/cc03a0759235c7c012fbd3de323c0eb08a8afcc0@news.nemoweb.net/Data/Media:1

**Comment by Julien-Arlandis** [comment]
Corrigé

**Comment by DuzzAtNemo** [comment]
OK. Issue "closed".
