### ISSUE TITLE
Balise [audio]

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#60]
Pour faciliter la compréhension et l'utilisation du bouton "Insérer un fichier audio", il faudrait que ce bouton ouvre une <div> ".insert_media", avec seulement la partie "Depuis une URL : ".

**Comment by Julien-Arlandis** [comment]
C'est fait.

**Comment by DuzzAtNemo** [comment]
OK, ça marche. Issue closed.
