### ISSUE TITLE
"PostingHost"

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#63]
Afficher l’adresse IP en clair, pour les articles publiés par un auteur non enregistré ?

**Comment by yamo-nntp** [comment]
Ce serait pas mal que ce soit configurable : soit tout le monde en clair, seuls les non authentifiés en clair, ou tout le monde en crypté.
De plus ce serait bien de mettre un Path indiquant si le post a un NNTP-Posting-Host  crypté ou pas : 

Non crypté :  nomduserveur.fqdn!from-jntp 
Crypté :  nomduserveur.fqdn!crypted!from-jntp

**Comment by DuzzAtNemo** [comment]
Je ne comprends pas le dernier point. Si l'article est publié sur un serveur JNTP, même par un auteur non enregistré, il n'y a pas de NNTP-Posting-Host ?

**Comment by yamo-nntp** [comment]
Non actuellement, c'est vu comme un serveur anonymisant comme terranews! Tout ça à cause d'un J à la place d'un N et d'un '-' manquant!

**Comment by Julien-Arlandis** [comment]
C'est configurable sur la nouvelle version du serveur, par défaut les IP sont en clair lorsque l'utilisateur n'est pas connecté.

**Comment by DuzzAtNemo** [comment]
OK. Je laisse le ticket ouvert, pour les demandes de yamo'.

**Comment by yamo-nntp** [comment]
Injection-Info est bien pris en compte.
