### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#64]
L’option "confirmSendArticle":"1" est bien sauvegardée à l’exportation et restituée à l’importation, mais la case n’est pas cochée dans "Préférences" => "Configuration du client".

**Comment by Julien-Arlandis** [comment]
Chez moi ça marche, Confirmer l'envoi d'un message est bien coché quand il le faut.

**Comment by DuzzAtNemo** [comment]
- Cocher "Confirmer l'envoi d'un message"
- Exporter le 'localStorage'
- Décocher "Confirmer l'envoi d'un message"
- Importer le 'localStorage'
- Actualiser la page

L'option reste décochée.

Pareil pour les autres options de l'onglet "Configuration du client".
Les fonctionnalités **cochées avant** l'exportation, sont bien implémentées après importation, mais les cases restent décochées.

**Comment by Julien-Arlandis** [comment]
Pas chez moi, l'option se recoche.

**Comment by DuzzAtNemo** [comment]
OK, j'ai vérifié avec Chrome et c'est donc lié à Firefox. Bizarrement, quand la fonctionnlité est **active**, mais la case **décochée**, Firebug m'affiche :
**`<input type="checkbox" checked="checked" value="1" id="confirm_send_article">`**

A tout hasard, il y a une autre différence. Avec Chrome, l'actualisation de l'onglet après importation, efface le contenu du **#txt_localStorage**. Dans Firefox, ce contenu est conservé.

**Comment by Julien-Arlandis** [comment]
Oui y a un bogue avec firefox sur le rafraichissement des checkbox, on en
avait déjà parlé.

**Comment by DuzzAtNemo** [comment]
OK je ferme le ticket.
