### ISSUE TITLE
ThreadID

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#66]
Quand le nombre d'articles dans un thread dépasse le "Nombre d'articles maximum à charger" :
- La fonctionnalité "voir tout le fil" tronque le début du fil. Exemple :
  http://news.nemoweb.net/?Jid=mr50ml$93j$1@shakotay.alphanet.ch + clic sur "voir tout le fil".
- L'URL avec le ThreadID affiche la page d'accueil du serveur, avant authentification. Exemple :
  http://news.nemoweb.net/?ThreadID=mr50ml$93j$1@shakotay.alphanet.ch

Ces problèmes peuvent-ils être résolus, en neutralisant la limite du "Nombre d'articles maximum à charger", dans le traitement du ThreadID ?

**Comment by DuzzAtNemo** [comment]
GitHub n'aime pas le $ dans les URL. Il faut les copier/coller dans le navigateur.

**Comment by Julien-Arlandis** [comment]
J'ai élargi à 1000 articles la propriété limit dans la requête (voir console). Les url avec ThreadID fonctionnent sur devnews.

**Comment by DuzzAtNemo** [comment]
OK. Issue closed.
