### ISSUE TITLE
Article marqué en favori

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#67]
Sélectionner nemo.\* => Marquer un article => Sélectionner un autre article => Sélectionner l’article marqué
=> Sélectionner nemo.\* :
Le marquage ‘favori’ est effacé.

NB : Remplacer "green" par "yellow" dans :

tr.favori {
     background-color: green;
     font-weight: normal !important;
}

**Comment by Julien-Arlandis** [comment]
Corrigé

**Comment by DuzzAtNemo** [comment]
Malgré plusieurs rafraîchissements, ça ne marche toujours pas chez moi. Après la re-sélection de nemo.*, le marquage ‘favori’ est effacé.

**Comment by Julien-Arlandis** [comment]
Il te faut vider le cache.

**Comment by DuzzAtNemo** [comment]
J'ai vidé le cache et le bogue est toujours présent. J'ai demandé une vérification sur 'nemo.dev.client'.

**Comment by DuzzAtNemo** [comment]
Entretemps j'ai aussi testé sur Chrome et constaté le même bogue.
EM a vérifié et confirme.
A noter que le marquage s'efface, quelle que soit la hiérarchie ou le groupe sélectionné à la dernière étape du test.
