### ISSUE TITLE
Lien <news:DataID>

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#68]
1 - Si le **DataID** n'est pas trouvé sur le serveur, 'devnews' n'affiche pas l'alerte _"Article non trouvé"_, en superposition à la page d'accueil.

2 - Actuellement, pour insérer un lien cliquable **news:DataID**, il faut partir d'un copier/coller du "DataID" de la source et compléter la syntaxe du lien manuellement. Pour un usage occasionnel, ce n'est pas une grosse contrainte. Par contre, pour signaler une rafale de spams, c'est un peu la galère.

Serait-il possible de créer un bouton qui réalise l'opération automatiquement, à partir de la sélection du "DataID" dans le corps de l'article ?

**Comment by Julien-Arlandis** [comment]
1 - Corrigé.

2 - Pourquoi pas un menu "Copier le DataID" depuis le menu contextuel ?

**Comment by DuzzAtNemo** [comment]
Ah que oui, voilà une idée qu'elle est bonne ... :+1: 
Je présume que la fonctionnalité va aussi ajouter le **`<news: ... >`** autour du DataID.

**Comment by yamo-nntp** [comment]
Je présume qu'on peut fermer.
