### ISSUE TITLE
Balise [spoil]

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#69]
Cette balise ne fonctionne pas :
- C'est OK dans "Aperçu", mais pas après envoi.
- L'article envoyé est vide, même s'il contient du texte hors de la balise.
- Il est impossible de "Répondre" à un tel article.

**Comment by Julien-Arlandis** [comment]
Corrigé

**Comment by DuzzAtNemo** [comment]
OK. Issue "closed".
