### ISSUE TITLE
Fonctionnalité "Voir tout le fil"

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#71]
Pour les articles d'origine NNTP, cette fonctionnalité est inopérante.
Le champ ThreadID n'est pas répliqué dans les réponses.
Exemple :
http://news.nemoweb.net/?Jid=6711b5ca576db0721c4b246b4b9b5106c053c61f@news.nemoweb.net

**Comment by Julien-Arlandis** [comment]
Corrigé.

**Comment by DuzzAtNemo** [comment]
Issue closed.
