### ISSUE TITLE
‘FromName’ et ‘FromMail’

### ISSUE THREAD

**Issue by DuzzAtNemo** [Julien-Arlandis/NemoClient#73]
Traitement et affichage des ‘FromName‘ et ‘FromMail‘ de la forme ‘frommail(FromName‘). Exemple : MacSoup.

Bon : http://news.nemoweb.net/?Jid=1mddg3u.tha2hiq1q5ylN%philo.ra@NoSm-freesurf.fr
Pas bon : http://devnews.nemoweb.net/?DataID=1mddg3u.tha2hiq1q5ylN%philo.ra@NoSm-freesurf.fr

**Comment by Julien-Arlandis** [comment]
Ça c'est un problème lié à la passerelle N2J, il faut le déplacer dans cette section.

**Comment by DuzzAtNemo** [comment]
Je n'ai pas d'accès à l'onglet "Issues" sur :
https://github.com/Julien-Arlandis/PHPN2J_Gateway

**Comment by Julien-Arlandis** [comment]
Moi non plus, peut être parce que c'est un fork.

**Comment by DuzzAtNemo** [comment]
En effet. Je propose donc de garder le ticket ici, car chez Gege ça risque de rester dans les oubliettes.

**Comment by yamo-nntp** [comment]
Bon j'ai forké (pas à l'aise avec git) : https://github.com/yamo-nntp/PHPN2J_Gateway

**Comment by DuzzAtNemo** [comment]
Je transfère le ticket et je le ferme ici.
